# Change these first
owner: Puppeteer-ai # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Puppeteer API
    url: https://api.puppeteerai.com/
  - name: Puppeteer Dashboard API
    url: https://dashboard-api.puppeteerai.com/api/health
  - name: Puppeteer Dashboard UI
    url: https://dashboard.puppeteerai.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: PuppeteerAI
  introTitle: "PuppeteerAI"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
  i18n:
    footer: [PuppeteerAI](https://puppeteerai.com/)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
